/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/hex/grass-hill.glb --output src/components/models/hex/GrassHill.tsx --types 
*/

import { useGLTF } from "@react-three/drei";
import type * as THREE from "three";
import type { GLTF } from "three-stdlib";
import { getAssetPath } from "~/utils/getAssetPath";

type GLTFResult = GLTF & {
	nodes: {
		"grass-hill_1": THREE.Mesh;
	};
	materials: {
		colormap: THREE.MeshStandardMaterial;
	};
};

const grassHill = getAssetPath("models/hex/grass-hill.glb");

export function GrassHill(props: JSX.IntrinsicElements["group"]) {
	const { nodes, materials } = useGLTF(grassHill) as GLTFResult;

	return (
		<group {...props} dispose={null}>
			<mesh
				geometry={nodes["grass-hill_1"].geometry}
				material={materials.colormap}
			/>
		</group>
	);
}

useGLTF.preload(grassHill);
