/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/hex/grass-forest.glb --output src/components/models/hex/GrassForest.tsx --types 
*/

import { useGLTF } from "@react-three/drei";
import type * as THREE from "three";
import type { GLTF } from "three-stdlib";
import { getAssetPath } from "~/utils/getAssetPath";

type GLTFResult = GLTF & {
	nodes: {
		"grass-forest_1": THREE.Mesh;
	};
	materials: {
		colormap: THREE.MeshStandardMaterial;
	};
};

const grassForest = getAssetPath("models/hex/grass-forest.glb");

export function GrassForest(props: JSX.IntrinsicElements["group"]) {
	const { nodes, materials } = useGLTF(grassForest) as GLTFResult;
	return (
		<group {...props} dispose={null}>
			<mesh
				geometry={nodes["grass-forest_1"].geometry}
				material={materials.colormap}
			/>
		</group>
	);
}

useGLTF.preload(grassForest);
