/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/scout.glb --output src/components/models/Scout.tsx --types 
*/

import { useGLTF } from "@react-three/drei";
import type * as THREE from "three";
import type { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
	nodes: {
		mesh_0: THREE.Mesh;
	};
	materials: object;
};

export function Scout(props: JSX.IntrinsicElements["mesh"]) {
	const { nodes } = useGLTF("/scout.glb") as GLTFResult;

	return (
		<mesh
			{...props}
			scale={0.5}
			geometry={nodes.mesh_0.geometry}
			material={nodes.mesh_0.material}
		/>
	);
}

useGLTF.preload("/scout.glb");
